stages:
  - build
  - publish
  
cache:
  key: npm-cache-v1
  paths:
    - node_modules

build_job:
  stage: build
  tags:
    - mac
  only:
    - tags
  script:
    - git clone -q https://gitlab-ci-token:$GITLAB_CI_TOKEN@gitlab.es.gov.br/SGPRJ/espm-ci-secrets.git > /dev/null 2>&1
    - cp espm-ci-secrets/.env .
    - cp -r espm-ci-secrets/ios/* .
    - npm i
    - npm run build:prod:ios
    - cordova platform add ios
    - cd platforms/ios
    - pod install
    - cd ../..
    - cordova build ios --buildConfig=ios-build.json --release --device
publish_job:
  stage: publish
  variables:
    GIT_STRATEGY: none
  tags:
    - mac
  only:
    - tags
  script:
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" fastlane ios beta
  dependencies:
    - build_job